config/routes.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#
# Reference: http://guides.rubyonrails.org/routing.html

VdsPip::Application.routes.draw do
  
  resources :users, :except => :show
  
  resources :projects, :only => [:index, :show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :tasks, :only => [:show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :folders, :only => [:show, :update] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create, :edit, :update]
    resources :dependencies, :only => :index
  end

  resources :documents, :only => [:show, :update, :destroy] do
    resources :versions, :only => [:new, :create]
  end

  resources :dependencies, :only => [ :create, :destroy ]

  resources :versions, :only => :show

  resources :locations, :only => :update # only for ajax call in item_drawer.js

  # match 'create_dependency_from' => 'dependencies#new'
  match 'items' => 'dependencies#items'
  
  match 'api/:action' => 'api#:action'

  root :to => "projects#index"
end

app/models/folder.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class Folder < ActiveRecord::Base
  include Container
  include Linkable
  self.include_root_in_json = false

  belongs_to :parent_folder, :class_name => "Folder"
  belongs_to :project
  # ONLY ONE of the above two pointers should be defined
  validate :exactly_one_parent_reference_defined

  def exactly_one_parent_reference_defined
    unless parent_folder_id.nil? ^ project_id.nil?
      errors[:base] << "Exactly one parent reference must be defined."
    end
  end

  has_many :documents
  has_many :folders, :foreign_key => 'parent_folder_id'
  has_many :downstream_dependencies, :as => :upstream_item, :class_name => "Dependency", :dependent => :destroy
  has_many :upstream_dependencies, :as => :downstream_item, :class_name => "Dependency", :dependent => :destroy
  belongs_to :task
  has_many :locations, :dependent => :destroy
  
  after_update :propagate_status!, :if => :status_changed?
  after_create :create_location_objects
  
  def create_location_objects
    User.all.each { |u|
      if u.is_member_of?(self.project)
        Location.create!(:folder_id => id, :user_id => u.id, :x => self.project.x, :y=>self.project.y)
      end
    }

    # Adjust location
    self.project.update_attribute(:x, self.project.x+10)
    self.project.update_attribute(:y, self.project.y+10)

    # # reset to zero if at screen size
    if self.project.x >= 600
      self.project.update_attribute(:x, 0)
    end
    if self.project.y >= 400
      self.project.update_attribute(:y, 0)
    end
  end
  
  # after_save callback. Sets the contents to have the same status as itself.
  def propagate_status!
    contents.each do |item|
      item.status = status
      item.save!
    end
  end

  def status
    @status ||= if contents.any? { |item| item.status == "not_updated" }
      "not_updated"
    else
      "up_to_date"
    end
  end

  def status=(val)
    status_will_change!
    @status = val
  end

  def status_will_change!
    begin
      value = status
      value = value.duplicable? ? value.clone : value
    rescue TypeError, NoMethodError
    end

    changed_attributes["status"] = value unless changed_attributes.include?("status")
  end

  def status_changed?
    changed_attributes.include?("status")
  end

  def contents
    documents + folders
  end

  def parent
    parent_folder || project
  end

  # return which project this folder is in
  alias_method :own_project_reference, :project
  def project
    own_project_reference || parent.project
  end

  def stage
    task.try(:stage)
  end

  def factor
    task.try(:factor)
  end
  
  # Gets this folder's location based on the current user's id
  def location
    locations.each do |location|
      return location if User.current.id == location.user_id
    end
    return nil
  end
  
  def coords
    return [self.location.x, self.location.y]
  end

  # This lets JS access these properties of folder - like in item_drawer.js, item.name works
  def serializable_hash(options = nil)
    {
      :name => name,
      :id => id,
      :coords => coords,
      :folders => folders,
      :documents => documents,
      :location_id => location.id
    }
  end
    
end

app/controllers/folders_controller.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class FoldersController < ApplicationController
  # GET /folders/1
  def show
    @folder = Folder.find(params[:id])
    @project = @folder.project
    @data = {
      :project => @project,
      :this_folder => dom_id(@folder),
      :dependencies => @folder.contained_dependencies
    }.to_json
  end

  # GET /tasks/1/folders/new OR /folders/1/folders/new
  def new
    @parent = get_parent_from_params
    @folder = @parent.folders.build
  end

  # POST /tasks/1/folders OR /folders/1/folders
  def create
    @parent = get_parent_from_params
    @folder = @parent.folders.build(params[:folder])

    if @folder.save
      Location.create!(:user_id=>current_user.id, :folder_id=>@folder.id)
      redirect_to(@parent, :notice => 'Folder was successfully created.')
    else
      render :action => "new"
    end
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  # PUT /folders/1
  def update
    @folder = Folder.find(params[:id])
    if @folder.update_attributes(params[:folder])
      # render(:json => nil, :status => :ok)
      redirect_to(@folder, :notice => 'Folder was successfully updated.')
    else
      # render(:json => @folder.errors, :status => :unprocessable_entity)
      render :action => "edit"
    end
  end
end

app/views/folders/edit.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<h1>Edit folder</h1>

<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/new.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<h1>New folder</h1>

<%= form_for([@parent, @folder]) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<!--no longer needed; this is the select field for tasks, which we want to hide so it defaults to nil task-->
	<%#= f.label :task_id %>
	<%#= collection_select :folder, :task_id, Task.all, :id, :name, { :prompt => "No task" } %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/show.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<p>Breadcrumbs: <%= breadcrumbs_for(@folder) %></p>
<p>
  <%= link_to "Create folder", new_folder_folder_path(@folder) %> &bull;
  <%= link_to "Edit folder", edit_folder_folder_path(@folder) %> &bull;
  To upload a document, double-click anywhere in the box.
</p>

<%= render :partial => "partials/pane_and_container" %>

<script type="text/javascript">
var Pip = Pip || {};
Pip.data = <%= raw(@data) %>;
Pip.data.containerId = 'container';
</script>