config/routes.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#
# Reference: http://guides.rubyonrails.org/routing.html

VdsPip::Application.routes.draw do
  
  resources :users, :except => :show
  
  resources :projects, :only => [:index, :show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :tasks, :only => [:show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :folders, :only => [:show, :update] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create, :edit, :update]
    resources :dependencies, :only => :index
  end

  resources :documents, :only => [:show, :update, :destroy] do
    resources :versions, :only => [:new, :create]
  end

  resources :dependencies, :only => [ :create, :destroy ]

  resources :versions, :only => :show

  resources :locations, :only => :update # only for ajax call in item_drawer.js

  # match 'create_dependency_from' => 'dependencies#new'
  match 'items' => 'dependencies#items'
  
  match 'api/:action' => 'api#:action'

  root :to => "projects#index"
end

app/models/user.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class User < ActiveRecord::Base
  # Sets up multiple threads so we can access User.current (which is current_user) in models
  # http://stackoverflow.com/questions/2513383/access-current-user-in-model, http://rails-bestpractices.com/posts/47-fetch-current-user-in-models
  def self.current
    Thread.current[:user]
  end
  def self.current=(user)
    Thread.current[:user] = user
  end
  
  
  attr_accessible :email, :password, :password_confirmation, :role, :project_tokens
  attr_reader :project_tokens # http://railscasts.com/episodes/258-token-fields
  
  attr_accessible :project_ids # needed for check box forms in users _form, when a normal user creates another user
  attr_accessor :password # getter and setter
  before_save :encrypt_password
  
  # These are user roles, mainly for control - not as important as actor roles
  ROLES = %w[site_admin project_manager normal_user]
  MINOR_ROLES = %w[project_manager normal_user] # for project managers to promote/demote
  ONLY_ROLE = %w[normal_user] # for a normal user creating another normal user
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  validates_presence_of :role
  validates_inclusion_of :role, :in => ROLES, :message => "^Nonexistent role."
  # validates_presence_of :actor_role
  # validates_inclusion_of :actor_role, :in => ACTOR_ROLES, :message => "^Nonexistent actor role."
  
  
  validate :email_formatted_correctly

  has_many :memberships
  has_many :projects, :through => :memberships
  has_many :locations
  
  after_create :create_memberships_for_site_admins
  
  def create_memberships_for_site_admins
    if role == 'site_admin'
      Project.all.each do |p|
        Membership.find_or_create_by_user_id_and_project_id(self.id, p.id)
      end
    end
  end

  def folders
  end

  # Setter method used by jQuery token input
  def project_tokens=(ids)
    self.project_ids = ids.split(",")
  end
  
  # Random 6-char password
  def self.generate_password
    ActiveSupport::SecureRandom.base64(6)
  end

  def is_member_of?(project)
    return self.memberships.any? { |m| m.project == project }
  end

  def self.authenticate(login, password)
    begin
      user = find(login)
    rescue ActiveRecord::RecordNotFound
      user = find_by_email(login)
    end

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def to_s
    self.email
  end

  # http://guides.rubyonrails.org/active_record_validations_callbacks.html
  def email_formatted_correctly
    unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      errors.add(:email, "is not a valid email")
    end
  end

  # For the current user, gets items without locations within the specified project
  # Used in after_filters within projects controller and folders controller for lazy loading
  def get_items_without_locations project
    arr = [ ]
    project.documents.each { |doc|
      arr.push doc if doc.location.nil? # doc.location returns nil if current user does not have a location for the doc
    }
    # add folders...
    return arr
  end
end

app/controllers/users_controller.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class UsersController < ApplicationController
  load_and_authorize_resource # checks actions (more specifically) based on ability.rb
	
  def new  
    @user = User.new
  end
    
  # POST /users/create
  # This action is designed to handle the submission of an html form for an admin.
  # For the similar api method, see ApiController#createuser
  def create  
    @user = User.new(params[:user])
    
    # for normal user making another user, only
    if logged_in_as_normal_user?
      # http://stackoverflow.com/questions/5054633/rails-3-has-many-through-form-with-checkboxes
      @user.attributes = {'project_ids' => []}.merge(params[:user] || {})
    end
    
    if @user.save  
      redirect_to root_url, :notice => "Signed up!"  
    else  
      render "new"  
    end  
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    # http://stackoverflow.com/questions/5054633/rails-3-has-many-through-form-with-checkboxes
    # @user.attributes = {'project_ids' => []}.merge(params[:user] || {})
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated."
      redirect_to users_path
    else
      render :action => :edit
    end
  end
  
  def index
    @site_admins = User.where(:role => 'site_admin')
    @project_managers = User.where(:role => 'project_manager')
    @normal_users = User.where(:role => 'normal_user')
  end
  
  # change later so no real deletion (?)
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/', :notice => "Account deleted."
  end
end

app/views/users/edit.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<!--users/edit-->
<div id="user_edit">
	<%= render :partial => "users/partials/form", :locals => { :user => @user, :button_name => "Update" } %>
	<% if can? :destroy, @user %>
		<!--CHANGE THIS TO NOT ACTUALLY DELETE LATER-->
		<%= link_to "Delete", @user, :method => :delete, :confirm => "Are you sure?" %>
	<% end %>
</div>

app/views/users/index.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>
<div id="users_index">
	<h1>Listing users</h1>

	<% if logged_in_as_site_admin? %>
		<!--Site admins-->
		<div id="site_admins">
			<span>Site Admins</span>
			<div id="site_admins_list">
				<ul class="user_list">
					<% @site_admins.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<%= link_to "Edit", [:edit,user], :class => "small_button" %>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>

		<div id="project_managers">
			<span>Project Managers</span>
			<div id="project_managers_list">
				<ul class="user_list">
					<% @project_managers.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<%= link_to "Edit", [:edit,user], :class => "small_button" %>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
	
		<div id="normal_users">
			<span>Normal Users</span>
			<div id="normal_users_list">
				<ul class="user_list">
					<% @normal_users.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<%= link_to "Edit", [:edit,user], :class => "small_button" %>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
	
		<%= link_to 'New User', new_user_path %>
		<!--end site admin-->
	<% elsif logged_in_as_project_manager? %>
		<!--Project managers-->
		<div id="project_managers">
			<span>Project Managers</span>
			<div id="project_managers_list">
				<ul class="user_list">
					<% @project_managers.select {|other_user| (other_user.project_ids & current_user.project_ids).present?}.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<%= link_to "Edit", [:edit,user], :class => "small_button" %>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
	
		<div id="normal_users">
			<span>Normal Users</span>
			<div id="normal_users_list">
				<ul class="user_list">
					<% @normal_users.select {|other_user| (other_user.project_ids & current_user.project_ids).present?}.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<%= link_to "Edit", [:edit,user], :class => "small_button" %>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
		<!--end project managers-->
	<% elsif logged_in_as_normal_user? %>
		<div id="normal_users">
			<span>Normal Users</span>
			<div id="normal_users_list">
				<ul class="user_list">
					<% @normal_users.select {|other_user| (other_user.project_ids & current_user.project_ids).present?}.each do |user| %>
						<%= content_tag_for :li, user do %>
							<ul class="items_within_user">
								<li class="email"><%= user.email %></li>
								<li class="controls">
									<i>no controls</i>
								</li>
							</ul>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
		
		<%= link_to 'New User', new_user_path %>
		<!--end normal users-->
	<% end %>
</div>

<%= link_to "Back", '/projects' %>

app/views/users/new.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<!--users/new-->
<div id="user_new">
	<%= render :partial => "users/partials/form", :locals => { :user => @user, :button_name => "Create" } %>
</div>