config/routes.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#
# Reference: http://guides.rubyonrails.org/routing.html

VdsPip::Application.routes.draw do
  
  resources :users, :except => :show
  
  resources :projects, :only => [:index, :show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :tasks, :only => [:show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :folders, :only => [:show, :update] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create, :edit, :update]
    resources :dependencies, :only => :index
  end

  resources :documents, :only => [:show, :update, :destroy] do
    resources :versions, :only => [:new, :create]
  end

  resources :dependencies, :only => [ :create, :destroy ]

  resources :versions, :only => :show

  resources :locations, :only => :update # only for ajax call in item_drawer.js

  # match 'create_dependency_from' => 'dependencies#new'
  match 'items' => 'dependencies#items'
  
  match 'api/:action' => 'api#:action'

  root :to => "projects#index"
end

app/models/document.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class Document < ActiveRecord::Base
  include Linkable
  self.include_root_in_json = false
  STATUSES = %w(up_to_date being_worked_on not_updated)
  attr_accessor :creating_FROM_dependency # a way to pass arbitrary form data for creating dependencies in _form
  attr_accessor :email
  
  # Relationships
  belongs_to :folder
  belongs_to :project
  belongs_to :task
  has_many :locations, :dependent => :destroy
  has_many :versions, :dependent => :destroy, :order => 'created_at DESC'
  has_many :downstream_dependencies, :as => :upstream_item, :class_name => "Dependency", :dependent => :destroy
  has_many :upstream_dependencies, :as => :downstream_item, :class_name => "Dependency", :dependent => :destroy
  
  accepts_nested_attributes_for :versions
  # accepts_nested_attributes_for :upstream_dependencies, :allow_destroy => true#,
  #   # :reject_if => lambda { |a| a[:email].blank?} # prevent submission of blank
  
  # Validations
  # validates_presence_of :folder_id, :task_id
  validate :exactly_one_parent_reference_defined
  validate :has_at_least_one_version
  validates_inclusion_of :status, :in => STATUSES
    
  # Hooks
  after_initialize :init
  after_update :mark_downstream_items_not_updated!, :if => Proc.new { |document| document.status_changed? && document.status == "not_updated" }
  after_create :create_location_objects, :set_task_id
  
  def exactly_one_parent_reference_defined
    unless folder_id.nil? ^ project_id.nil?
      errors[:base] << "Exactly one parent reference must be defined."
    end
  end
  
  def create_location_objects
    User.all.each { |u|
      if u.is_member_of?(self.project) || ( !self.folder.nil? && u.is_member_of?(self.folder.project) )
        Location.create!(:document_id => id, :user_id => u.id)
      end
    }
  end

  def mark_downstream_items_not_updated!
    downstream_items.each do |item|
      item.status = "not_updated"
      item.save!
    end
  end

  def init
    self.status ||= 'up_to_date'
  end

  def stage
    task.try(:stage) # task may not exist
  end

  def factor
    task.try(:factor) # task may not exist
  end

  # return folder if it exists, otherwise project
  def parent
    folder || project
  end

  def has_at_least_one_version
    if versions.empty?
      errors.add(:versions, "must have at least one version")
    end
  end
  def icon_path
    latest_version.try(:icon_path)
  end

  def latest_version
    versions.first
  end
  
  # Gets this document's location based on the current user's id
  def location
    locations.each do |location|
      return location if User.current.id == location.user_id
    end
    return nil
    # Abandoned:
    # Lazy initialization - only reached if no location for this document and user
    # final_location = Location.create!(:document_id => self.id, :user_id => User.current.id)
    # return final_location
    # Why can't this see that the location already exists? Making it once should be enough.
    # Different threads. That would explain it. But no.
  end
  
  def coords
    return [self.location.x, self.location.y]
  end
  
  # Why?
  def name
    read_attribute(:name) || latest_version.name
  end

  def serializable_hash(options = nil)
    {
      :name => name,
      :id => id,
      :status => status,
      :coords => coords,
      :icon => icon_path,
      :location_id => location.id
    }
  end
  
  private
    def set_task_id
      if self.folder_id
        self.update_attribute(:task_id, get_task_from_folder(self.folder_id))
      end
    end
    
    def get_task_from_folder(folder_id)
      folder = Folder.find(folder_id)
      while folder.task_id.nil? && folder.project_id.nil?
        folder = Folder.find(folder.parent_folder.id)
      end
      return folder.task_id
    end
end

app/controllers/documents_controller.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class DocumentsController < ApplicationController
  # GET /documents/1
  def show
    @document = Document.find(params[:id])
  end

  # GET /folders/1/documents/new OR /tasks/1/documents/new
  def new
    @parent = get_parent_from_params
    @document = @parent.documents.build
    @document.versions.build
  end

  # POST /folders/1/documents OR /tasks/1/documents
  def create
    @parent = get_parent_from_params # parent is either folder or project; see application_controller
    @document = @parent.documents.build(params[:document])
    if @document.save
      redirect_to(@document, :notice => 'Document was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /documents/1
  # this is sometimes called with coords, sometimes with in-place edits
  def update
    @document = Document.find(params[:id])
    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.json { render :json => nil, :status => :ok }
        format.html { redirect_to(@document, :notice => 'Document was successfully updated.') }
      else
        format.json { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    head :ok
  end

end

app/views/documents/new.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<h1>New document</h1>

<%= form_for([@parent, @document], :html => {:multipart => true}) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for(:versions) do |version_fields| %>
    <div class="field">
      <%= version_fields.label :file, "Upload a file:" %> <%= version_fields.file_field :file %>
    </div>
    - OR -
    <div class="field">
      <%= version_fields.label :external_url, "Link to a web address:" %> <%= version_fields.text_field :external_url, :type => 'url' %>
    </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/show.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>
<!--This is what you see when you double-click on a document-->
<%= div_for @document do %>
  <h1>
  	<%= image_tag(@document.icon_path, :class => "main-icon") %><input data-in-place-edit="true" id="document_name" name="document[name]" size="30" type="text" value="<%= @document.name %>" />
	</h1>
  <div class="info">
		<!--Basic information-->
    <div class="basic-info">
      <% unless @document.description.blank? %>
      <p class="description"><%= @document.description %></p>
      <% end %>
      <ul class="metadata">
	
			<% if @document.task.nil? %>
	      <li>Task: <%= "(none)" %>
	      <li>Stage: <%= "(none)" %>
	      <li>Factor: <%= "(none)" %>
			<% else %>
			  <li>Task: <%= @document.task.name %>
	      <li>Stage: <%= @document.task.stage.name %>
	      <li>Factor: <%= @document.task.factor.name %>
			<% end %>
	
      <li>Actors: [to be implemented]</li>
      </ul>
    </div>
		<!--Dependencies-->
		<table>
			<caption>Dependencies</caption>
	      <tr>
	        <th>Type</th>
	        <th>Target</th>
				</tr>
		  <% @document.upstream_dependencies.each do |dep| %>
	      <tr>
	        <td>From</td>
	        <td><%= dep.upstream_item.name %></td>
					<td><%= link_to "X", dep, :method=>:delete, :remote => true, :class=>'x_button' %></td>
	      </tr>
	    <% end %>
	    <% @document.downstream_dependencies.each do |dep| %>
	      <tr>
	        <td>To</td>
	        <td><%= dep.downstream_item.name %></td>
					<td><%= link_to "X", dep, :method=>:delete, :remote => true, :class=>'x_button' %></td>
	      </tr>
	    <% end %>
		</table>
	
		<!--Versions-->
    <table class="versions">
      <caption>All versions:</caption>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Author</th>
        <th>Created on</th>
			</tr>
    <% @document.versions.each do |version| %>
      <tr>
        <td><%= image_tag version.icon_path, :size => '15x15' %></td>
        <td><%= link_to version.name, version %></td>
        <td>[author]</td>
        <td><%= version.created_at.to_s(:long) %></td>
      </tr>
    <% end %>
    </table>
  </div>
	
	<!--Buttons-->
  <div class="actions">
    <%= link_to("Download", @document.latest_version, :class => 'btn') %>
    <%= link_to("Update", new_document_version_path(@document), :class => 'btn') %>
    <%= link_to("Delete", @document, :confirm => 'Are you sure?', :method => :delete, :class => 'btn') %>
    <h2>Status:</h2>
    <ul class="radio">
      <% Document::STATUSES.each do |status| %>
        <li>
          <%= label_tag("document_status_#{status}", radio_button(:document, :status, status, "data-in-place-edit" => true) + status.humanize()) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<script type="text/javascript">
$(".x_button").click(function() {
	$(this).css('display','none');
	alert('Dependency removed');
});
</script>