config/routes.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#
# Reference: http://guides.rubyonrails.org/routing.html

VdsPip::Application.routes.draw do
  
  resources :users, :except => :show
  
  resources :projects, :only => [:index, :show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :tasks, :only => [:show, :new, :create] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create]
  end

  resources :folders, :only => [:show, :update] do
    resources :documents, :only => [:new, :create]
    resources :folders, :only => [:new, :create, :edit, :update]
    resources :dependencies, :only => :index
  end

  resources :documents, :only => [:show, :update, :destroy] do
    resources :versions, :only => [:new, :create]
  end

  resources :dependencies, :only => [ :create, :destroy ]

  resources :versions, :only => :show

  resources :locations, :only => :update # only for ajax call in item_drawer.js

  # match 'create_dependency_from' => 'dependencies#new'
  match 'items' => 'dependencies#items'
  
  match 'api/:action' => 'api#:action'

  root :to => "projects#index"
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :document
  validate :file_xor_url
  after_create :mark_document_up_to_date!, :unless => Proc.new { |version|
    version.document.upstream_items.any? { |item| item.status == "not_updated" } ||
    version.document.versions.size < 2 # (don't mark the document updated if this is its first version)
  }
  after_create { |version| version.document.mark_downstream_items_not_updated! }
  mount_uploader :file, DocumentUploader

  def mark_document_up_to_date!
    document.status = "up_to_date"
    document.save!
  end

  # must have a file or a url but not both
  def file_xor_url
    unless external_url.blank? ^ file.blank?
      errors[:base] << "Choose a file or a link but not both."
    end
  end

  def icon_path
    # return something like '/images/icons/folder.png'
    # TODO
    '/images/icons/unknown.png'
  end

  def name
    # for files, use the filename. for urls, use the url?
    if file.blank?
      external_url
    else
      filename
    end
  end

  def filename
    self[:file]
  end
end

app/controllers/versions_controller.rb
#
# Authors: Jeff Cox, David Zhang
# Copyright Syracuse University
#

class VersionsController < ApplicationController
  # GET /versions/1
  def show
    @version = Version.find(params[:id])
    unless @version.external_url.blank?
      redirect_to @version.external_url
    else
      send_file @version.file.file.file
    end
  end

  # GET /documents/1/versions/new
  def new
    @document = Document.find(params[:document_id])
    @version = @document.versions.build
  end

  # POST /documents/1/versions
  def create
    @document = Document.find(params[:document_id])
    @version = @document.versions.build(params[:version])

    if @version.save
      redirect_to(@document, :notice => 'Version was successfully created.')
    else
      render :action => "new"
    end
  end
end

app/views/versions/new.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<h1>New version</h1>

<%= form_for([@document, @version], :html => {:multipart => true}) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file, "Upload a file:" %> <%= f.file_field :file %>
  </div>
  - OR -
  <div class="field">
    <%= f.label :external_url, "Link to a web address:" %> <%= f.text_field :external_url, :type => 'url' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/show.html.erb
<%#
Authors: Jeff Cox, David Zhang
Copyright Syracuse University
%>

<p id="notice"><%= notice %></p>

<p>
  <b>Document:</b>
  <%= @version.document %>
</p>

<p>
  <b>External url:</b>
  <%= @version.external_url %>
</p>

<p>
  <b>File:</b>
  <%= @version.file %>
</p>


<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>